### ISSUE TITLE
Cannot read property 'is_student' of undefined

### ISSUE THREAD

**Issue by rade98** [justdjango/teach-me-django#2]
Hi,
I'm following first video from youtube about this project. I have some issues with login, register is working fine.
When I try to login, it''s giving 200 status but it's returning error like "Cannot read property 'is_student' of undefined" what is the problem here?

**Comment by rade98** [comment]
I found that in auth on line 52 and 53
is_student: res.data.user_type.is_student,
is_teacher: res.data.user_type.is_teacher,

If i set is_student: true or false, it's giving a same error for the teacher, and if I set teacher true or false it's working. What could be the problem? I watched the video again and couldn't fix it.

**Comment by lunyamwi** [comment]
Go to Layout.js and add this there below
 is_student: state.auth.is_student,
