### ISSUE TITLE
npm install fail 

### ISSUE THREAD

**Issue by RajlaxmiSen** [justdjango/teach-me-django#3]
npm install on Windows Powershell fail and shows following error msg 

![Screenshot (16)](https://user-images.githubusercontent.com/21692017/61791131-bd5d8300-ae36-11e9-88a0-ed73fb93acb6.png)

 and here is the log file
[2019-07-24T10_20_33_794Z-debug.log](https://github.com/justdjango/teach-me-django/files/3426630/2019-07-24T10_20_33_794Z-debug.log)

I am trying to find out the issues but failed.

**Comment by mattfreire** [comment]
Try a different node version. It's difficult to tell exactly what could be causing that for you
