### ISSUE TITLE
django.db.utils.OperationalError: no such table: users_user

### ISSUE THREAD

**Issue by ghost** [justdjango/teach-me-django#8]
I have this error when i try to register an account: django.db.utils.OperationalError: no such table: users_user and a response: "POST /rest-auth/registration/ HTTP/1.1" 500 26685. Can someone help me. Ps: I also try the migrate the database in a frech install but that error is still there.
Thank You

**Comment by ekofi** [comment]
Same error here. What was the solution?

**Comment by ekofi** [comment]
Solved. Use `python manage.py migrate --run-syncdb`
